### ISSUE TITLE
Mac High Sierra not working?

### ISSUE THREAD

**Issue by bddvlpr** [Mic238/osu-for-Mac-Stable-Latest#1]
If i doublepress it, it opens up Wineskin with 4 options:
Install software
Set Screen Options
Advanced
Quit

How do i get it working?

**Comment by Mic238** [comment]
Try to move the **whole folder** to application, as long as the old client is not replaced, the data won't be lost.
Or, go to advance then test run.
I built the package under high sierra so there should be no compatible problem here.
