### ISSUE TITLE
proxy issues

### ISSUE THREAD

**Issue by novice8012** [Mic238/osu-for-Mac-Stable-Latest#13]
Is that possible to add proxy settings to mac osu? I tried global proxy with shadowsocksR and referred to this "https://www.quora.com/How-do-I-configure-proxy-for-IE-that-runs-on-Wine" but they both did not work. As I know, Wineskin does not do its own networking but use normal Internet connection, so is there something special with osu?

**Comment by Mic238** [comment]
As far as I know, osu itself doesn't support the use of proxy or vpn and would possibly result in banning account
