### ISSUE TITLE
Installer broke

### ISSUE THREAD

**Issue by WabMiran** [Mic238/osu-for-Mac-Stable-Latest#14]
It keeps saying its updating, gets to 100. and then starts again!!!

IT DOESNT EVER GO TO GAME OR ANYTHING ELSE. THE GAME UPDATE THING BBROKEE

**Comment by Mic238** [comment]
Have you changed the installation path as instructed on step 3.3? If it's not changed, wine would keep opening the installer and the installer would keep installing in some random location. The actual game will never open because wine doesn't know the exact location of the game.
