### ISSUE TITLE
game error at launch

### ISSUE THREAD

**Issue by Tronald1** [Mic238/osu-for-Mac-Stable-Latest#15]
it updated correctly as the update logs show, but when i attempt to launch the game it comes up with this error http://prntscr.com/l5i6v3
reddit post i made about the same thing it has a video and other info that may be useful https://www.reddit.com/r/osugame/comments/9npei3/osx_attempting_to_get_osu_to_open_and_this/

**Comment by Mic238** [comment]
Hey can you provide more info like what system version are you running on and the error log from wine? If you right click the osu app - show package content - double open wineskin - advance - test run, it will produce the log

**Comment by Tronald1** [comment]
heres a pastebin of the error log
https://pastebin.com/KUXuZRFw
this is the second time this error as occurred, so i doubt redownloading would help, i am probably doing some part of the procedure wrong so dont go assuming its something wrong with your code yet
