### ISSUE TITLE
wine issues

### ISSUE THREAD

**Issue by novice8012** [Mic238/osu-for-Mac-Stable-Latest#16]
While I open osu on macos majove 10.14, the process tccd may take up to 300% of CPU and make my mac stuck. A possible similar report about the matter: https://forums.macrumors.com/threads/10-4-9th-beta-and-wine-and-tccd-process.2134338/ The tccd locates at /system/library/privateframeworks⁩/TCC.framework⁩/⁨Versions⁩/⁨A⁩. Is there any possible means to fix this out?

**Comment by Mic238** [comment]
Happened on mine as well. Just force quit it on the activity monitor as a temp solution. 

This seems to be the problem on wineskin, not wine or crossover, so it needs to move out of wineskin to be fixed. But really as you know, lazer is coming out soon and the current client will be outdated, so I don't think there's a need to fix this.
