### ISSUE TITLE
loops on "Hi! Your game client is being updated"

### ISSUE THREAD

**Issue by ghost** [Mic238/osu-for-Mac-Stable-Latest#19]
when I start this up the first time it shows a window "Installing to Z:\...\Application Support\osu!" (I chose the install directory myself) then it shows "Updating your game client"

Progress bar goes from 0% to 100%, the window closes.... then opens again

"Updating your game client"

Gets to 100%.... loops forever, the "updating game client" window closes and opens and loads to 100% then closes then opens forever (well, at least the hour that I let it do this for)

log output: https://gist.github.com/theonlygusti/da88b0de7f491fd3856f1edd4df1422b

**Comment by Mic238** [comment]
Please refer to step 3 sub 3, you need to change the install location to drive_c/program files/osu to have it work. You can't just choose a random location because wine wouldn't know where it is
