### ISSUE TITLE
Infinite "Your game client is getting updated" message loop

### ISSUE THREAD

**Issue by Yaroster** [Mic238/osu-for-Mac-Stable-Latest#22]
<img width="375" alt="Screen Shot 2019-11-08 at 6 25 01 PM" src="https://user-images.githubusercontent.com/39062152/68483493-1e2d9180-0255-11ea-9bb7-d36cc9a3b192.png">
I am currently getting this message in loop, the updater is finishing the update and relaunching itself.

**Comment by Mic238** [comment]
Duplicate #19 Refers to step 3.3 you need to select the correct install location
