### ISSUE TITLE
Problem with install: soft link files

### ISSUE THREAD

**Issue by fr42k** [Mic238/osu-for-Mac-Stable-Latest#8]
For link files below, it seems that they lost their source files.
```
cp: osu!.app/Contents/Frameworks/libXplugin.1.0.dylib: No such file or directory
cp: osu!.app/Contents/Frameworks/libXplugin.1.dylib: No such file or directory
cp: osu!.app/Contents/Frameworks/libXplugin.dylib: No such file or directory
```

Thx.

**Comment by Mic238** [comment]
Can you briefly describe what did you do for these errors?

**Comment by fr42k** [comment]
I downloaded the zip file, then unzip it. Then ```sudo cp -rf osu\!.app /Applications``` , and after this, osu! appeared in the applications, but there is no effect when I clicked the icon to open it.

**Comment by Mic238** [comment]
I would advise you use drag n drop on finder window instead of `cp -rf`, as cp would not copy the softlink but the actual pointed file instead, which causes the problem.

The other option you can do is use `cp -a` which would keep the link as it is.
